services:
  # WhatsApp HTTP API (WAHA) service
  - type: web
    name: waha
    runtime: image
    image: docker.io/devlikeapro/waha:latest
    plan: starter
    envVars:
      - key: WAHA_API_KEY
        sync: false
      - key: WAHA_PRINT_QR
        value: "true"
